import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from "next/link";
import s from './layout.module.scss';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <nav className={s.nav}>
          <Link href="/">Главная</Link>
          <Link href="/notes">Заметки</Link>
      </nav>
      <div className={s.content}>
          {children}
      </div>
      </body>
    </html>
  )
}
